FROM dunglas/frankenphp

# add additional extensions here:
RUN install-php-extensions \
	pcntl \
	pdo_mysql \
	curl \
	zip 

COPY . /app



# Set any ENVs
ARG APP_NAME=${APP_NAME}
ARG APP_ENV=${APP_ENV}
ARG APP_KEY=${APP_KEY}
ARG APP_DEBUG=${APP_DEBUG}
ARG APP_URL=${APP_URL}

ARG LOG_CHANNEL=${LOG_CHANNEL}

ARG DB_CONNECTION=${DB_CONNECTION}
ARG DB_HOST=${DB_HOST}
ARG DB_PORT=${DB_PORT}
ARG DB_DATABASE=${DB_DATABASE}
ARG DB_USERNAME=${DB_USERNAME}
ARG DB_PASSWORD=${DB_PASSWORD}

ARG BROADCAST_DRIVER=${BROADCAST_DRIVER}
ARG CACHE_DRIVER=${CACHE_DRIVER}
ARG QUEUE_CONNECTION=${QUEUE_CONNECTION}
ARG SESSION_DRIVER=${SESSION_DRIVER}
ARG SESSION_LIFETIME=${SESSION_LIFETIME}
ARG FILESYSTEM_DRIVER=${FILESYSTEM_DRIVER}

ARG REDIS_HOST=${REDIS_HOST}
ARG REDIS_PASSWORD=${REDIS_PASSWORD}
ARG REDIS_PORT=${REDIS_PORT}

ARG CORS=${CORS}
ARG CORS_ALLOW=${CORS_ALLOW}
ARG FRONT_END_URL=${FRONT_END_URL}
ARG SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}


ARG MAIL_MAILER=${MAIL_MAILER}
ARG MAIL_HOST=${MAIL_HOST}
ARG MAIL_PORT=${MAIL_PORT}
ARG MAIL_USERNAME=${MAIL_USERNAME}
ARG MAIL_PASSWORD=${MAIL_PASSWORD}
ARG MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
ARG MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
ARG MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
ARG MAIL_FROM_NAME=${APP_NAME}

ARG PUSHER_APP_ID=${PUSHER_APP_ID}
ARG PUSHER_APP_KEY=${PUSHER_APP_KEY}
ARG PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
ARG PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}

ARG AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ARG AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
ARG AWS_BUCKET=${AWS_BUCKET}


ARG MIX_PUSHER_APP_KEY=${MIX_PUSHER_APP_KEY}
ARG MIX_PUSHER_APP_CLUSTER=${MIX_PUSHER_APP_CLUSTER}

# Install composer
COPY --from=composer/composer:2 /usr/bin/composer /usr/local/bin/composer

RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader

RUN composer dump-autoload --no-interaction --no-dev --optimize


RUN chmod -R 775 storage
RUN chmod -R 775 bootstrap


CMD php artisan migrate

EXPOSE 80

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]